ARG POSTGRES_VERSION
FROM postgres:${POSTGRES_VERSION}-alpine3.22

ENV BUILD_DEPS="build-base git clang llvm lld"
RUN apk add --no-cache --virtual .build-deps ${BUILD_DEPS} && \
  git clone --depth=1 https://github.com/citusdata/pg_cron /tmp/pg_cron && \
  mkdir -p "/usr/lib/llvm19/bin"; \
  for t in llvm-config clang clang++ llvm-ar llvm-ranlib llvm-lto; do \
    if command -v "$t" >/dev/null 2>&1; then \
      ln -sf "$(command -v "$t")" "/usr/lib/llvm19/bin/$t"; \
    fi; \
  done; \
  make -C /tmp/pg_cron \
  CLANG="$(command -v clang)" \
  LLVM_CONFIG="$(command -v llvm-config)" \
  LLVM_AR="$(command -v llvm-ar)" \
  LLVM_RANLIB="$(command -v llvm-ranlib)" \
  LLVM_LTO="$(command -v llvm-lto)" && \
  make -C /tmp/pg_cron install && \
  rm -rf /tmp/pg_cron && \
  apk del .build-deps && \
  echo "shared_preload_libraries = 'pg_cron'" >> /usr/local/share/postgresql/postgresql.conf.sample
